/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/execucoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar execuções, todas ou de um labirinto
         * @description Sem o parâmetro, devolve 4x4, 8x4 e 12x4 na mesma lista. Com labirinto, devolve só o tipo pedido. Quando não há execução em andamento, o primeiro item é a execução mais recente já encerrada.
         */
        get: operations["listarExecucoes"];
        put?: never;
        /**
         * Registra uma nova execução, contando 1/3 tentativas.
         * @description O operador informa o labirinto. O backend abre a execução lógica, começa o relógio de 10 minutos e cria a tentativa 1. Se já houver execução em andamento, ela é cancelada.
         */
        post: operations["novaExecucao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/execucoes/em-andamento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca dos dados da execução em andamento (ao vivo)
         * @description No máximo uma execução fica em_andamento. A tela carrega o resultado desta busca e depois assina o stream. Registrar esta rota antes de /execucoes/{execucao_id}.
         */
        get: operations["buscarExecucaoEmAndamento"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/execucoes/{execucao_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar uma execução, com trajeto, tentativas e health-check
         * @description Devolve trajeto, tentativas e health-check para reexibir o percurso, inclusive depois de a execução encerrar. O acompanhamento ao vivo continua no stream.
         */
        get: operations["buscarExecucao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/execucoes/{execucao_id}/encerrar-tentativa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerrar a tentativa aberta, mantendo a execução em andamento
         * @description A tentativa passa a ser failed com origem encerrado_operador. A execução lógica permanece em_andamento, para a retomada. O backend passa a devolver `{"v":1,"cmd":"interromper"}` em `comandos` em todo POST /telemetria até a confirmação do robô ou nova tentativa.
         */
        post: operations["encerrarTentativa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/execucoes/{execucao_id}/retomar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abrir a tentativa seguinte depois de uma falha
         * @description O pedido não tem corpo. Em caso de sucesso a resposta é o retorno da tentativa 2 ou 3. Recusa com 409 e não cria tentativa quando já existe tentativa aberta, quando as três já foram usadas ou quando a execução está cancelada.
         */
        post: operations["retomarTentativa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/execucoes/{execucao_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eventos da execução ao vivo
         * @description Fluxo de eventos do servidor para o navegador. O campo event repete o tipo do JSON em data. No evento passo, a linha id é o passo_id. Ao reconectar, o navegador envia esse valor em Last-Event-ID e o backend reenvia os passos posteriores. A amostra telemetria não entra nesse replay.
         */
        get: operations["abrirStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receber uma linha de telemetria da ponte
         * @description Corpo **EntradaPonte** (4.4.1): a ponte repassa a linha crua lida da serial e o instante `recebido_em` com fuso horário. Toda validação do JSON serial v1 fica no backend. Linha aceita ou descartada só em log (seq repetido, sem tentativa aberta, hc_item fora do health-check) responde 200; rota 501 até BACK-02 concluir a ingestão. Após **Encerrar tentativa**, a resposta inclui o comando de interrupção em `comandos` em todo POST até a `falha` com `origem` = `web` ou nova tentativa; a ponte escreve cada item na serial sem traduzir.
         */
        post: operations["receberTelemetria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Labirinto: "4x4" | "8x4" | "12x4";
        /** @enum {string} */
        StatusExecucao: "em_andamento" | "concluida" | "cancelada";
        /** @enum {string} */
        StatusTentativa: "health-check" | "running" | "success" | "failed";
        /** @enum {string} */
        TipoInicio: "nova" | "retomada";
        /**
         * @description Tipo lido no DIP. invalido é o código 11 e reprova o health-check.
         * @enum {string}
         */
        TipoDip: "4x4" | "8x4" | "12x4" | "invalido";
        /** @enum {string} */
        Componente: "bateria" | "tof_frontal_esq" | "tof_frontal_dir" | "tof_esquerdo" | "tof_direito" | "motor_esquerdo" | "motor_direito" | "encoder_esquerdo" | "encoder_direito";
        /** @enum {string} */
        MotivoFalha: "collision" | "stuck" | "out_of_track" | "time_exceeded" | "falha_componente" | "low_battery" | "health_check_failed" | "link_lost" | "encerrado_operador";
        /**
         * @description Motivos que o operador pode escolher ao encerrar a tentativa.
         * @enum {string}
         */
        MotivoEncerramento: "collision" | "stuck" | "out_of_track";
        /**
         * @description Origem gravada em FALHA. O valor web/boot da linha serial vira encerrado_operador.
         * @enum {string}
         */
        OrigemFalha: "automatica" | "encerrado_operador";
        /** @enum {string} */
        MotivoRecusa: "tentativa_aberta" | "limite_3" | "execucao_cancelada";
        /** @enum {string} */
        Rumo: "N" | "S" | "L" | "O";
        /** @enum {string} */
        EixoLongo: "x" | "y";
        NovaExecucao: {
            tipo_labirinto: components["schemas"]["Labirinto"];
        };
        /** @description Retorno ao abrir uma tentativa. Em POST /execucoes, attempt_index é 1. Em POST /execucoes/{id}/retomar, é 2 ou 3. */
        RetornoNovaExecucao: {
            /** Format: uuid */
            execucao_id: string;
            /** Format: uuid */
            tentativa_id: string;
            attempt_index: number;
        };
        EncerrarTentativa: {
            motivo: components["schemas"]["MotivoEncerramento"];
            observacao?: string | null;
        };
        ItemHealthCheck: {
            componente: components["schemas"]["Componente"];
            aprovado: boolean;
            valor_lido?: number | null;
        };
        Falha: {
            motivo: components["schemas"]["MotivoFalha"];
            origem: components["schemas"]["OrigemFalha"];
            celula_x: number;
            celula_y: number;
            componente?: components["schemas"]["Componente"] | null;
            observacao?: string | null;
            /** Format: date-time */
            momento_falha: string;
        };
        Tentativa: {
            /** Format: uuid */
            tentativa_id: string;
            attempt_index: number;
            status: components["schemas"]["StatusTentativa"];
            tipo_inicio: components["schemas"]["TipoInicio"];
            tipo_dip?: components["schemas"]["TipoDip"] | null;
            /** Format: date-time */
            iniciada_em: string;
            /** Format: date-time */
            encerrada_em?: string | null;
            tempo_s?: number | null;
            /** @description Metros por segundo. Distância em células vezes 180 mm, dividida pelo tempo. */
            velocidade_media?: number | null;
            /** @description Tensão em volts no início da tentativa. */
            bateria_inicial?: number | null;
            bateria_final?: number | null;
            /** @description Queda de tensão (bateria_inicial − bateria_final), em volts. */
            consumo_bateria?: number | null;
            health_check: components["schemas"]["ItemHealthCheck"][];
            falha?: components["schemas"]["Falha"] | null;
        };
        PassoTrajeto: {
            /** @description Também é o id do evento SSE passo. */
            passo_id: number;
            seq: number;
            x: number;
            y: number;
            /** @description N = 1, S = 2, L = 4, O = 8. */
            paredes_mask: number;
            retomada: boolean;
            /** Format: date-time */
            entrou_em?: string;
        };
        LeituraTelemetria: {
            ordem: number;
            x: number;
            y: number;
            /** @description Tensão em volts, convertida de bat_mv. */
            bateria: number;
            /** @description Metros por segundo, convertidos de vel_mm_s. */
            velocidade?: number | null;
            rumo?: components["schemas"]["Rumo"] | null;
            /** Format: date-time */
            enviado_em: string;
        };
        /** @description Retrato usado por GET /execucoes/em-andamento e GET /execucoes/{id}. Trajeto, health-check e falha começam vazios e são preenchidos por linhas novas, não por este POST de criação. */
        ExecucaoDetalhe: {
            /** Format: uuid */
            execucao_id: string;
            tipo_labirinto: components["schemas"]["Labirinto"];
            status: components["schemas"]["StatusExecucao"];
            tentativas_usadas: number;
            /** Format: date-time */
            iniciada_em: string;
            /** Format: date-time */
            encerrada_em?: string | null;
            tempo_total_s?: number | null;
            /** @description Variação percentual contra o melhor tempo do mesmo labirinto. Negativo quando esta execução foi mais rápida. Null se não houver marca anterior. */
            variacao_melhor_tempo_pct?: number | null;
            /** @description Eixo em que o 8x4 ou o 12x4 se estende. Null no 4x4 e enquanto o robô não entrou numa célula além do canto 4x4. */
            eixo_longo?: components["schemas"]["EixoLongo"] | null;
            /**
             * Format: date-time
             * @description Recebimento da última mensagem. A interface compara este instante com o relógio. Aos 10 s sem mensagem a execução passa a cancelada, com link_lost.
             */
            ultima_mensagem_em?: string | null;
            tentativas: components["schemas"]["Tentativa"][];
            trajeto: components["schemas"]["PassoTrajeto"][];
            /** @description Leituras da tentativa aberta, ou as últimas se já estiver encerrada. */
            leituras: components["schemas"]["LeituraTelemetria"][];
        };
        ResumoExecucao: {
            /** Format: uuid */
            execucao_id: string;
            tipo_labirinto: components["schemas"]["Labirinto"];
            status: components["schemas"]["StatusExecucao"];
            tentativas_usadas: number;
            /** Format: date-time */
            iniciada_em: string;
            /** Format: date-time */
            encerrada_em?: string | null;
            tempo_total_s?: number | null;
            /** @description Velocidade média da última tentativa, em metros por segundo. */
            velocidade_media?: number | null;
            /** @description Queda de tensão da última tentativa concluída (bateria_inicial − bateria_final), em volts. */
            consumo_bateria?: number | null;
        };
        EventoTelemetria: {
            /** @enum {string} */
            tipo: "telemetria";
            ordem: number;
            x: number;
            y: number;
            bateria: number;
            velocidade?: number | null;
            rumo?: components["schemas"]["Rumo"] | null;
            eixo_longo?: components["schemas"]["EixoLongo"] | null;
            /** Format: date-time */
            enviado_em: string;
        };
        EventoPasso: {
            /** @enum {string} */
            tipo: "passo";
            passo_id: number;
            seq: number;
            x: number;
            y: number;
            paredes_mask: number;
            retomada: boolean;
            /** Format: date-time */
            entrou_em?: string;
        };
        EventoStatus: {
            /** @enum {string} */
            tipo: "status";
            /** Format: uuid */
            tentativa_id: string;
            attempt_index: number;
            status_tentativa: components["schemas"]["StatusTentativa"];
            status_execucao: components["schemas"]["StatusExecucao"];
            tipo_dip?: components["schemas"]["TipoDip"] | null;
        };
        EventoHealthCheck: {
            /** @enum {string} */
            tipo: "health_check";
            /** Format: uuid */
            tentativa_id: string;
            componente: components["schemas"]["Componente"];
            aprovado: boolean;
            valor_lido?: number | null;
        };
        EventoFalha: {
            /** @enum {string} */
            tipo: "falha";
            /** Format: uuid */
            tentativa_id: string;
            motivo: components["schemas"]["MotivoFalha"];
            origem: components["schemas"]["OrigemFalha"];
            celula_x: number;
            celula_y: number;
            componente?: components["schemas"]["Componente"] | null;
            observacao?: string | null;
            /** Format: date-time */
            momento_falha: string;
            status_execucao: components["schemas"]["StatusExecucao"];
        };
        EventoSucesso: {
            /** @enum {string} */
            tipo: "sucesso";
            /** Format: uuid */
            tentativa_id: string;
            x: number;
            y: number;
            status_execucao: components["schemas"]["StatusExecucao"];
        };
        Comando: {
            /** @enum {integer} */
            v: 1;
            /** @enum {string} */
            cmd: "interromper";
        };
        EntradaPonte: {
            /** @description Linha lida da serial, sem o \\n, sem alteração. */
            linha: string;
            /**
             * Format: date-time
             * @description Instante em que a ponte leu a linha, com fuso horário.
             */
            recebido_em: string;
        };
        RespostaPonte: {
            /**
             * @description Comandos para a ponte escrever na serial (JSON compacto + \\n). Vazio quando não há downlink pendente.
             * @default []
             */
            comandos: components["schemas"]["Comando"][];
        };
        Recusa: {
            motivo: components["schemas"]["MotivoRecusa"];
            /** Format: date-time */
            ocorrida_em: string;
        };
        ErroNaoEncontrado: {
            detail: string;
        };
        ErroValidacao: {
            detail: {
                loc?: string[];
                msg?: string;
                type?: string;
            }[];
        };
    };
    responses: {
        /** @description Não há execução com esse execucao_id. */
        NaoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "Execução não encontrada."
                 *     }
                 */
                "application/json": components["schemas"]["ErroNaoEncontrado"];
            };
        };
        /** @description A retomada foi recusada. Nenhuma tentativa nova é gravada. O motivo diz se já havia tentativa aberta, se as três já foram usadas ou se a execução está cancelada. */
        Recusa: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Recusa"];
            };
        };
        /** @description Corpo ou parâmetro fora do contrato. */
        ErroValidacao: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErroValidacao"];
            };
        };
    };
    parameters: {
        ExecucaoId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarExecucoes: {
        parameters: {
            query?: {
                /** @example 4x4 */
                tipo_labirinto?: components["schemas"]["Labirinto"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de execuções, da mais recente para a mais antiga. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumoExecucao"][];
                };
            };
        };
    };
    novaExecucao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "tipo_labirinto": "4x4"
                 *     }
                 */
                "application/json": components["schemas"]["NovaExecucao"];
            };
        };
        responses: {
            /** @description Execução criada com sucesso, contando 1/3 tentativas. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "execucao_id": "123e4567-e89b-12d3-a456-426614174000",
                     *       "tentativa_id": "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                     *       "attempt_index": 1
                     *     }
                     */
                    "application/json": components["schemas"]["RetornoNovaExecucao"];
                };
            };
            422: components["responses"]["ErroValidacao"];
        };
    };
    buscarExecucaoEmAndamento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Há uma execução em andamento. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoDetalhe"];
                };
            };
            /** @description Não há execução em andamento, então o corpo vem vazio. A execução mais recente já encerrada é o primeiro item de GET /execucoes. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buscarExecucao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: components["parameters"]["ExecucaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execução encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoDetalhe"];
                };
            };
            404: components["responses"]["NaoEncontrado"];
        };
    };
    encerrarTentativa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: components["parameters"]["ExecucaoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncerrarTentativa"];
            };
        };
        responses: {
            /** @description Tentativa encerrada. O corpo é a execução com a tentativa failed e a execução ainda em_andamento, quando cabe retomada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoDetalhe"];
                };
            };
            404: components["responses"]["NaoEncontrado"];
            422: components["responses"]["ErroValidacao"];
        };
    };
    retomarTentativa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: components["parameters"]["ExecucaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nova tentativa aberta. attempt_index é 2 ou 3. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetornoNovaExecucao"];
                };
            };
            404: components["responses"]["NaoEncontrado"];
            409: components["responses"]["Recusa"];
        };
    };
    abrirStream: {
        parameters: {
            query?: never;
            header?: {
                /** @description passo_id do último passo já aplicado na tela. */
                "Last-Event-ID"?: number;
            };
            path: {
                execucao_id: components["parameters"]["ExecucaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fluxo text/event-stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NaoEncontrado"];
        };
    };
    receberTelemetria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "linha": "{\"v\":1,\"boot\":7,\"seq\":42,\"t_ms\":1200,\"tipo\":\"tel\",\"estado\":\"running\",\"x\":0,\"y\":2,\"rumo\":\"N\",\"bat_mv\":7810,\"vel_mm_s\":210,\"eixo_longo\":null}",
                 *       "recebido_em": "2026-10-05T14:03:21.512-03:00"
                 *     }
                 */
                "application/json": components["schemas"]["EntradaPonte"];
            };
        };
        responses: {
            /** @description Linha processada (persistida ou descartada com registro em log). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaPonte"];
                };
            };
            /** @description Linha inválida (mais de 256 B, JSON inválido, v ≠ 1, campo faltando ou fora da faixa, célula fora do labirinto). A ponte não deve reenviar 4xx. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroValidacao"];
                };
            };
        };
    };
}
