site_name: 2026.2 PI1 Grupo 01 Juliana
site_url: https://pi1-2026-2.github.io/2026_2_PI1_Grupo01_Juliana/
repo_url: https://github.com/PI1-2026-2/2026_2_PI1_Grupo01_Juliana
theme:
  name: material
markdown_extensions:
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js