"""schema_inicial_der

Revision ID: 88a55c282858
Revises: 
Create Date: 2026-10-04 22:34:42.893740

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88a55c282858'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labirinto',
    sa.Column('labirinto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=5), nullable=False),
    sa.Column('largura', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('labirinto_id'),
    sa.UniqueConstraint('tipo', name='uq_labirinto_tipo')
    )
    op.create_table('execucao_logica',
    sa.Column('execucao_id', sa.UUID(), nullable=False),
    sa.Column('labirinto_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tentativas_usadas', sa.Integer(), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tempo_total_s', sa.Numeric(), nullable=True),
    sa.CheckConstraint("status IN ('em_andamento', 'concluida', 'cancelada')", name='ck_execucao_logica_status'),
    sa.CheckConstraint('tentativas_usadas BETWEEN 0 AND 3', name='ck_execucao_logica_tentativas_usadas'),
    sa.ForeignKeyConstraint(['labirinto_id'], ['labirinto.labirinto_id'], ),
    sa.PrimaryKeyConstraint('execucao_id')
    )
    op.create_table('parede_celula',
    sa.Column('parede_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('execucao_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('norte', sa.Boolean(), nullable=False),
    sa.Column('sul', sa.Boolean(), nullable=False),
    sa.Column('leste', sa.Boolean(), nullable=False),
    sa.Column('oeste', sa.Boolean(), nullable=False),
    sa.Column('detectada_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucao_logica.execucao_id'], ),
    sa.PrimaryKeyConstraint('parede_id'),
    sa.UniqueConstraint('execucao_id', 'x', 'y', name='uq_parede_execucao_celula')
    )
    op.create_table('tentativa',
    sa.Column('tentativa_id', sa.UUID(), nullable=False),
    sa.Column('execucao_id', sa.UUID(), nullable=False),
    sa.Column('attempt_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tipo_inicio', sa.String(), nullable=False),
    sa.Column('tipo_descoberto', sa.String(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tempo_s', sa.Numeric(), nullable=True),
    sa.Column('velocidade_media', sa.Numeric(), nullable=True),
    sa.Column('bateria_inicial', sa.Numeric(), nullable=True),
    sa.Column('bateria_final', sa.Numeric(), nullable=True),
    sa.Column('consumo_bateria', sa.Numeric(), nullable=True),
    sa.CheckConstraint("status IN ('health-check', 'running', 'success', 'failed')", name='ck_tentativa_status'),
    sa.CheckConstraint("tipo_inicio IN ('nova', 'retomada')", name='ck_tentativa_tipo_inicio'),
    sa.CheckConstraint('attempt_index BETWEEN 1 AND 3', name='ck_tentativa_attempt_index'),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucao_logica.execucao_id'], ),
    sa.PrimaryKeyConstraint('tentativa_id'),
    sa.UniqueConstraint('execucao_id', 'attempt_index', name='uq_tentativa_execucao_attempt')
    )
    op.create_index('uq_tentativa_aberta_por_execucao', 'tentativa', ['execucao_id'], unique=True, postgresql_where=sa.text("status IN ('health-check', 'running')"))
    op.create_table('tentativa_rejeitada',
    sa.Column('rejeicao_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('execucao_id', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('ocorrida_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("motivo IN ('tentativa_aberta', 'limite_3', 'execucao_cancelada')", name='ck_tentativa_rejeitada_motivo'),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucao_logica.execucao_id'], ),
    sa.PrimaryKeyConstraint('rejeicao_id')
    )
    op.create_table('falha',
    sa.Column('falha_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tentativa_id', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('celula_x', sa.Integer(), nullable=True),
    sa.Column('celula_y', sa.Integer(), nullable=True),
    sa.Column('componente', sa.String(), nullable=True),
    sa.Column('observacao', sa.String(length=100), nullable=True),
    sa.Column('momento_falha', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("motivo IN ('collision', 'stuck', 'out_of_track', 'time_exceeded', 'falha_componente', 'low_battery', 'health_check_failed', 'link_lost', 'encerrado_operador')", name='ck_falha_motivo'),
    sa.CheckConstraint("origem IN ('automatica', 'encerrado_operador')", name='ck_falha_origem'),
    sa.ForeignKeyConstraint(['tentativa_id'], ['tentativa.tentativa_id'], ),
    sa.PrimaryKeyConstraint('falha_id'),
    sa.UniqueConstraint('tentativa_id')
    )
    op.create_table('health_check_item',
    sa.Column('item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tentativa_id', sa.UUID(), nullable=False),
    sa.Column('componente', sa.String(), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('valor_lido', sa.Numeric(), nullable=True),
    sa.Column('verificado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("componente IN ('bateria', 'tof_frontal_esq', 'tof_frontal_dir', 'tof_esquerdo', 'tof_direito', 'motor_esquerdo', 'motor_direito', 'encoder_esquerdo', 'encoder_direito')", name='ck_health_check_item_componente'),
    sa.ForeignKeyConstraint(['tentativa_id'], ['tentativa.tentativa_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('leitura_telemetria',
    sa.Column('leitura_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tentativa_id', sa.UUID(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('fase', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('bateria', sa.Numeric(), nullable=True),
    sa.Column('velocidade', sa.Numeric(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("fase IN ('health-check', 'running')", name='ck_leitura_telemetria_fase'),
    sa.ForeignKeyConstraint(['tentativa_id'], ['tentativa.tentativa_id'], ),
    sa.PrimaryKeyConstraint('leitura_id'),
    sa.UniqueConstraint('tentativa_id', 'ordem', name='uq_leitura_tentativa_ordem')
    )
    op.create_index('ix_leitura_telemetria_tentativa_leitura', 'leitura_telemetria', ['tentativa_id', 'leitura_id'], unique=False)
    op.create_table('passo_trajeto',
    sa.Column('passo_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tentativa_id', sa.UUID(), nullable=False),
    sa.Column('execucao_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('paredes_mask', sa.Integer(), nullable=True),
    sa.Column('retomada', sa.Boolean(), nullable=False),
    sa.Column('entrou_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucao_logica.execucao_id'], ),
    sa.ForeignKeyConstraint(['tentativa_id'], ['tentativa.tentativa_id'], ),
    sa.PrimaryKeyConstraint('passo_id'),
    sa.UniqueConstraint('execucao_id', 'seq', name='uq_passo_execucao_seq')
    )
    op.create_index('ix_passo_trajeto_execucao_passo', 'passo_trajeto', ['execucao_id', 'passo_id'], unique=False)
    op.execute(
        sa.text(
            """
            INSERT INTO labirinto (labirinto_id, tipo, largura, altura) VALUES
            (1, '4x4', 4, 4),
            (2, '8x4', 8, 4),
            (3, '12x4', 12, 4)
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_passo_trajeto_execucao_passo', table_name='passo_trajeto')
    op.drop_table('passo_trajeto')
    op.drop_index('ix_leitura_telemetria_tentativa_leitura', table_name='leitura_telemetria')
    op.drop_table('leitura_telemetria')
    op.drop_table('health_check_item')
    op.drop_table('falha')
    op.drop_table('tentativa_rejeitada')
    op.drop_index('uq_tentativa_aberta_por_execucao', table_name='tentativa', postgresql_where=sa.text("status IN ('health-check', 'running')"))
    op.drop_table('tentativa')
    op.drop_table('parede_celula')
    op.drop_table('execucao_logica')
    op.drop_table('labirinto')
    # ### end Alembic commands ###

